site_name: FaBo JetRacer Docs
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    palette:
      primary: 'green'
      accent: 'black'
    logo: 'logo.png'
    favicon: 'favicon.png'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - attr_list
nav:
  - Home: "index.md"
  - 1.はじめに: "00.はじめに/start.md"
  - 2.組立:
    - 型番の確認: "01.組み立て/01.check.md"
    - JR1_S_C_F:
      - 部品リスト: "01.組み立て/carbon_edition/JR1_S_C_F/07.bom_CarbonEdition_F.md"
      - 組立手順: "01.組み立て/carbon_edition/JR1_S_C_F/08.build_Carbon_F.md"
    - JR1_S_C_E:
      - 部品リスト: "01.組み立て/carbon_edition/JR1_S_C_E/07.bom_CarbonEdition_E.md"
      - 組立手順: "01.組み立て/carbon_edition/JR1_S_C_E/08.build_Carbon_E.md"
    - JR1_S_C_D:
      - 部品リスト: "01.組み立て/carbon_edition/JR1_S_C_D/07.bom_CarbonEdition_D.md"
      - 組立手順: "01.組み立て/carbon_edition/JR1_S_C_D/08.build_Carbon_D.md"
    - JR1_S_C_C:
      - 部品リスト: "01.組み立て/carbon_edition/JR1_S_C_C/07.bom_CarbonEdition_C.md"
      - 組立手順: "01.組み立て/carbon_edition/JR1_S_C_C/08.build_Carbon_C.md"
    - JR1_S_C_B:
      - 部品リスト: "01.組み立て/carbon_edition/JR1_S_C_B/07.bom_CarbonEdition_B.md"
      - 組立手順: "01.組み立て/carbon_edition/JR1_S_C_B/08.build_Carbon_B.md"
    - JR1_S_C:
      - 部品リスト: "01.組み立て/carbon_edition/JR1_S_C/05.bom_CarbonEdition.md"
      - 組立手順: "01.組み立て/carbon_edition/JR1_S_C/06.build_Carbon.md"
    - 旧式:
      - 部品リスト: "01.組み立て/old/00.bom.md"
      - 組立手順: "01.組み立て/old/01.build2.md"
  - 3.設定:
    - Wi-Fiの設定: "03.設定/01.intro.md"
  - 4.Quick Start:
    - 基本編: "quick/01.intro.md"
  - 5.学習と走行:
    - 使用するNotebook: "04.学習/01.notebooks.md"
    - PWMの設定: "04.学習/02.pwm.md"
    - 走行録画: "04.学習/09.recordCamera.md"
    - 画像カット: "04.学習/03.filecut.md"
    - アノテーションと学習: "04.学習/03.interactive_regression.md"
    - TensorRTへの変換: "04.学習/04.optimize_model.md"
    - 自動走行: "04.学習/05.run.md"
    - クラウドによる学習: "04.学習/08.googleColab.md"
    - 受信機信号計測: "04.学習/10.transmitterSignal.md"
    - 検証動画作成: "04.学習/11.makeMovie.md"
    - アノテーション: "04.学習/07.remark.md"
  - 6.Orin Nano:
    - SDカードの焼込: "orin/01.sd.md"
    - Dockerの構築: "orin/02.docker.md"
  - 7.その他:
    - SDカードの焼込: "sd_fabo/01.image.md"
    - SDカードの新規作成:
      - SDカードの焼込: "sd_new/01.jetpack46.md"
      - 初期設定: "sd_new/02.setting.md"
      - Wi-Fiの設定: "sd_new/03.wifi.md"
      - パッケージの作成: "sd_new/04.jetcard.md"
      - NXへの対応: "sd_new/05.nx.md"
    - イメージの作成:
      - 事前処理: "sd_write/01.save.md"
      - SDカードからイメージ抜出し: "sd_write/02.dd.md"
      - SDカード用圧縮イメージ: "sd_write/03.parted.md"
    - 拡張ルーター(旧式):
      - 設定: "network/01.router.md"
      - 接続: "network/04.connect.md"
    - Wi-Fi関連:
      - Wi-Fiの設定: "sd_fabo/02.wifi.md"
      - ネットワーク構成: "network/00.layout.md"
      - 割振られたIPの確認: "network/02.ifconfig.md"
      - 8265経由で接続: "network/03.8265.md"
    - 各種Tips:
      - Tips: "tips/01.tips.md"
      - 接続トラブル: "tips/02.wificonectionhadling.md"
      - CPU FAN制御方法: "tips/03.fancontrol.md"
  - 8.単体パーツ情報:
    - ControllerBoard:
      - 612 Jetracer Rev3.0.0,1,2 : "parts/01.jr612030002.md"
      - 612 Jetracer Rev3.0,4 : "parts/02.jr612030004.md"
      - 612 Jetracer Rev2.0.29 : "parts/jr612020029.md"
      - XIAO Firmwareの更新 : "parts/Firmware.md"


extra_css:
#  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
#  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
#  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css"
  - "css/version-select.css"
  - "css/custom.css"
extra_javascript:
  - javascripts/version-select.js
  - javascripts/extra.js
plugins:
  - macros